#Env
env = _JAVA_AWT_WM_NONREPARENTING,1
env = MOZ_ENABLE_WAYLAND,1
env = MOZ_DISABLE_RDD_SANDBOX,1

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,wayland
env = XDG_CONFIG_HOME,/home/mehandes/.config

env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1 

env = GDK_BACKEND,wayland,x11
env = XCURSOR_SIZE,22

env = NVD_BACKEND,direct
env = WLR_NO_HARDWARE_CURSORS,1
env = CLUTTER_BACKEND,wayland
env = SDL_VIDEODRIVER,wayland

#Desktop
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia
#env = LIBVA_DRIVER_NAME,nvidia

#XWayland
xwayland {
  force_zero_scaling = 1
}

#Monitor
monitor=eDP-1,highres,0x0,1
monitor=HDMI-A-1,highres,0x0,1 

#Exec
exec-once = waybar
exec-once = hyprpaper

#Input
input {
  force_no_accel = 1
  repeat_rate = 50
  repeat_delay = 375
  follow_mouse = 2
  sensitivity = 0
  force_no_accel = 1
  float_switch_override_focus = 0
	kb_layout = us,ru
	kb_options = grp:win_space_toggle
}

#General
general {
    gaps_in = 6
    gaps_out = 10
    border_size = 0
    layout = dwindle
}

#Decoration
decoration {
    rounding = 10
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = $base 
}

#Animations
animations {
    enabled = yes

    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1

    animation = windows, 1, 5, overshot, slide
    animation = windowsOut, 1, 4, overshot, slide 
    animation = windowsMove, 1, 4, default
    animation = border, 1, 10, default
    animation = fade, 1, 5, smoothIn
    animation = fadeDim, 1, 5, smoothIn
    animation = workspaces, 1, 6, default
}

#Layouts
dwindle {
    no_gaps_when_only = false
    pseudotile = yes
    preserve_split = yes
}

#Misc
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    animate_mouse_windowdragging = false
    mouse_move_focuses_monitor = false
    focus_on_activate = true
    enable_swallow = false
}

#Binds

$mainMod = SUPER

#Apps
bind = $mainMod, Return, exec, alacritty
bind = $mainMod, F, exec, pkill wofi || wofi --show drun

#Windows
bind = $mainMod, C, killactive, 
bind = $mainMod, P, pseudo,
bind = $mainMod, V, togglefloating,
bind = $mainMod, G, fullscreen,

#Focus 
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

#Move
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

#Workspace
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

#Move
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

#Resize
bind = $mainMod CTRL, H, resizeactive, -20 0
bind = $mainMod CTRL, L, resizeactive, 20 0
bind = $mainMod CTRL, K, resizeactive, 0 -20
bind = $mainMod CTRL, J, resizeactive, 0 20
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
